### ISSUE TITLE
CoreML Model Compiler Error Group

### ISSUE THREAD

**Issue by mattjis** [alicanbatur/HotDogDetector#1]
VGG16.mlmodel: unable to read document

I'm really keen to test this out but am quite new to Xcode :( Let me know what I'm doing wrong! Thanks

**Comment by alicanbatur** [comment]
VGG16 is a large sized lib. You can download it from [here](https://developer.apple.com/machine-learning/). Then add it to your project :)

**Comment by jackrex** [comment]
why choose VGG16？ Inception V3 is enough

**Comment by alicanbatur** [comment]
Of course it can also be done with the library. Your decision
I was hanging out between the libraries, the fact that it was attached to the project for the last time it stayed.
